# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pr: none
schedules:
- cron: "0 12 * * 2"
  displayName: Weekly Tuesday snippets updates
  always: true

pool:
  vmImage: 'windows-2019'

variables:
  graphDocsRepo: 'https://github.com/andrueastman/microsoft-graph-docs.git'
  snippetInjectionRepo: 'https://github.com/andrueastman/apidoctor.git'
  snippetInjectionBranch: 'scheduled-snippets-injection'
  graphDocsPath: 'GraphDocs'
  snippetInjectionPath: 'ApiDoctor'
  solution: '$(snippetInjectionPath)/**/*.sln'
  snippetApiUrl: 'https://graphexplorerapi.azurewebsites.net/api/GraphExplorerSnippets'
  snippetLanguages: 'C#,Javascript,Objective-C,Java'

steps:
- checkout: none  # Don't sync sources since its just an automation task.

- task: PowerShell@1
  displayName: "Clone Microsoft Graph Docs"
  inputs:
    scriptType: inlineScript
    inlineScript: "git clone -b master '$(graphDocsRepo)' --recurse-submodules '$(graphDocsPath)' 2>&1 | Write-Host"

- task: PowerShell@1
  displayName: "Clone Snippet injection tool"
  inputs:
    scriptType: inlineScript
    inlineScript: "git clone -b '$(snippetInjectionBranch)' '$(snippetInjectionRepo)' --recurse-submodules '$(snippetInjectionPath)' 2>&1 | Write-Host"

- task: NuGetToolInstaller@0
  displayName: "Install Nuget.exe"

- task: NuGetCommand@2
  displayName: "Restore Packages for  Snippets Injection Tool"
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  displayName: "Build Source for Snippets Injection Tool"
  inputs:
    solution: '$(solution)'
    platform: 'Any CPU'
    configuration: 'Release'

- task: CmdLine@2
  displayName: "Run snippet injection against docs"
  inputs:
    script: |
      cd $(graphDocsPath)
      git config --global user.name "Eastman"
      git config --global user.email "v-anomon@microsoft.com"
      ..\\$(snippetInjectionPath)\\ApiDoctor.Console\\bin\\Release\\apidoc.exe generate-snippets --ignore-warnings --path . --snippet-api-url $(snippetApiUrl) --lang $(snippetLanguages) --github-token $(githubToken) --git-path "C:\Program Files\Git\bin\git.exe" --commit-message "Scheduled snippets update" --pull-request-title "Snippets Update"