# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pr: none

pool:
  vmImage: 'windows-2019'

variables:
  graphDocsRepo: 'https://github.com/andrueastman/microsoft-graph-docs.git'
  snippetInjectionRepo: 'https://github.com/andrueastman/apidoctor.git'
  snippetInjectionBranch: 'rework-snippet-injection'
  graphDocsPath: 'GraphDocs'
  snippetInjectionPath: 'ApiDoctor'
  solution: '$(snippetInjectionPath)/**/*.sln'
  snippetApiUrl: 'https://graphexplorerapi.azurewebsites.net/api/GraphExplorerSnippets'
  snippetLanguages: 'C#,Javascript,Objective-C,Java'

steps:
- task: PowerShell@1
  displayName: "Clone Microsoft Graph Docs"
  inputs:
    scriptType: inlineScript
    inlineScript: "git clone -b master '$(graphDocsRepo)' --recurse-submodules '$(graphDocsPath)' 2>&1 | Write-Host"

- task: PowerShell@1
  displayName: "Clone Snippet injection tool"
  inputs:
    scriptType: inlineScript
    inlineScript: "git clone -b '$(snippetInjectionBranch)' '$(snippetInjectionRepo)' --recurse-submodules '$(snippetInjectionPath)' 2>&1 | Write-Host"

- task: NuGetToolInstaller@0
  displayName: "Install Nuget.exe"

- task: NuGetCommand@2
  displayName: "Restore Packages for  Snippets Injection Tool"
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  displayName: "Build Source for Snippets Injection Tool"
  inputs:
    solution: '$(solution)'
    platform: 'Any CPU'
    configuration: 'Release'

- task: CmdLine@2
  displayName: "Run snippet injection against docs"
  inputs:
    script: |
      $(snippetInjectionPath)\\ApiDoctor.Console\\bin\\Release\\apidoc.exe generate-snippets --ignore-warnings --path $(graphDocsPath) --snippet-api-url $(snippetApiUrl) --lang $(snippetLanguages) --github-token 1022e82c3086a9c560bc7a0789676d8d36d84280 --git-path "C:\Program Files\Git\bin\git.exe"
      